version: '3.8'

services:
  storage-service:
    build: .
    container_name: storage-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=1433
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Добавляем Adminer для удобного управления базой данных (опционально)
  adminer:
    image: adminer
    container_name: storage-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - storage-network
    depends_on:
      - storage-service

networks:
  storage-network:
    driver: bridge
