version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: storage-service-dev
    container_name: storage-service-dev
    restart: unless-stopped
    ports:
      - "3005:3005"
      - "9229:9229" # Для отладки
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_POOL_MAX=${DB_POOL_MAX}
      - DB_POOL_MIN=${DB_POOL_MIN}
      - DB_IDLE_TIMEOUT=${DB_IDLE_TIMEOUT}
      - DB_ENCRYPT=${DB_ENCRYPT}
      - DB_ENABLE_ARITH_ABORT=${DB_ENABLE_ARITH_ABORT}
      - DB_TRUST_SERVER_CERTIFICATE=${DB_TRUST_SERVER_CERTIFICATE}
      - LOG_LEVEL=debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - storage-network-dev
    command: npm run dev

  # Добавляем Adminer для удобного управления базой данных (опционально)
  adminer:
    image: adminer
    container_name: storage-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - storage-network-dev
    depends_on:
      - app

networks:
  storage-network-dev:
    driver: bridge 